music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :show, :create]
  resources :bands, except: [:show]
  resources :bands, only: [:show] do 
    resources :albums, only: [:show]
  end
  resources :albums, except: [:show] do 
    resources :tracks, only: [:show]
  end
  resources :tracks, except: [:show]
end

music_app/app/models/album.rb
class Album < ApplicationRecord
    validates :title, :year, :band_id, presence: true
    validates :studio, inclusion: { in: [true, false]}

    belongs_to :band,
        foreign_key: :band_id,
        class_name: :Band

    has_many :tracks,
        foreign_key: :album_id,
        class_name: :Track

end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
    validates :name, presence: true

    has_many :albums,
        foreign_key: :band_id,
        class_name: :Album
end

music_app/app/models/track.rb
class Track < ApplicationRecord
    validates :title, :ord, :album_id, presence: true
    validates :regular, inclusion: { in: [true, false]}

    belongs_to :album,
        foreign_key: :album_id,
        class_name: :Album

end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
    validates :password, length: {minimum: 6, allow_nil: true}
    validates :email, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :session_token, uniqueness: true
    before_validation :ensure_session_token

    attr_reader :password

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            user
        else
            nil
        end
    end

    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def new
        render :new
    end

    def create
        @album = Album.new(title: params[:album][:title],year: params[:album][:year],band_id: params[:album][:band_id],studio: params[:album][:studio])
        if @album.save
            redirect_to band_album_url(@album.band_id, @album.id)
        else
            flash[:errors] = ["Please fill everything out"]
            render :new
        end
    end

    def show
        @album = Album.find(params[:id])
        render :show
    end

    def destroy
        @album = Album.find(params[:id])
        @album.delete
        redirect_to band_url(@album.band_id)
    end

    private

    def album_params
        params.require(:album).permit(:studio, :title, :year, :band_id)
    end

end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout!
        current_user.reset_session_token! 
        session[:session_token] = nil
    end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    
    def index 
        render :index
    end
    def new
        @user = current_user
        render :new
    end

    def create
        @band = Band.new(name: params[:band][:name])
        if @band.save
            redirect_to band_url(@band)
        else
            flash[:errors] = ["Name cannot be blank"]
            redirect_to new_band_url
        end
    end

    def show
        @band = Band.find(params[:id])
        render :show
    end

    def destroy
        @band = Band.find(params[:id])
        @band.delete
        redirect_to band_url(@band)
    end

    private

    def band_params
        params.require(:band).permit(:name)
    end

end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def index
        render :new
    end

    def new
        render :new
    end

    def create
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if user
            login!(user)
            redirect_to user_url(user)
        else
            flash.now[:errors] = ["Invalid email or password"]
            render :new
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
end

music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    def new
        render :new
    end

    def create
        @track = Track.new(title: params[:track][:title],ord: params[:track][:ord],album_id: params[:track][:album_id],regular: params[:track][:regular])
        if @track.save
            redirect_to album_url(@track.album_id)
        else
            flash[:errors] = ["Please fill everything out"]
            render :new
        end
    end

    def show
        @track = Track.find(params[:id])
        render :show
    end

    def destroy
        @track = Track.find(params[:id])
        @track.delete
        redirect_to album_url(@track.album_id)
    end

    private

    def track_params
        params.require(:track).permit(:regular, :title, :ord, :album_id)
    end

end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new 
        render :new
    end

    def create
        @user = User.new(email: params[:user][:email], password: params[:user][:password])
        if @user.save
            login!(@user)
            redirect_to user_url(@user.id)
        else
            flash[:errors] = ["Account cannot be created"]
            redirect_to new_user_url
        end
    end

    def show
        @user = current_user
        render :show
    end

    private

    def user_params
        params.require(:user).permit(:email, :password)
    end

end

music_app/app/helpers/application_helper.rb
module ApplicationHelper

    def randomized_background_image
        images = ['1.jpeg', '2.jpeg']
        images[rand(images.size)]
    end
      
end

music_app/app/helpers/session_helper.rb
module SessionHelper
end

music_app/app/helpers/users_helper.rb
module UsersHelper
end

music_app/app/views/albums/new.html.erb
<form id="login" action="<%= albums_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= session[:authenticity_token] %>">
        <label for="band_id">
                Made By: 
                <select name="album[band_id]">
                        <option disabled selected> Choose a band </option>
                    <% Band.all.each do |band| %>
                        <option name="album[band_id]" value="<%= band.id %>"><%= band.name %></option>
                    <% end %>
                </select>
            </label>
            <br/>
        <label for="title">
            Album Title: 
            <input type="text" name="album[title]"> 
        </label>
        <br/>
        <label for="year">
            Album Year: 
            <input type="text" name="album[year]"> 
        </label>
        <br/>
        <label for="studio_type">
            Recorded: 
            <input type="radio" name="album[studio]" value="true">Studio</input>
            <input type="radio" name="album[studio]" value="false"> Album</input>
        </label>
        <br/>
        <br/>
        <input type="Submit" value="Add Album">    
</form>

music_app/app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
<br/>
<div id="login">
Band: <%= Band.find_by(id: params[:band_id]).name %>
<br/>
Title: <%= @album.title %>
<br/>
Year Recorded: <%= @album.year %>
<br/>
Album Type: <%= @album.studio ? "Studio" : "Live" %>
<br/>
</div>
<br/>

<form action="<%= album_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= session[:authenticity_token] %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Delete This Album">
</form>

music_app/app/views/bands/index.html.erb
  
    <% Band.all.each do |band| %>
    <a href="<%= band_url(band) %>"><h1><%= band.name %></a></h1>
    <% end %>

music_app/app/views/bands/new.html.erb
<form id="login" action="<%= bands_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= session[:authenticity_token] %>">
    <label for="band_name">
        Band Name 
        <br/>
        <input type="text" name="band[name]"> 
    </label>
    <br/>
    <br/>
    <input type="Submit" value="Create Band">    
</form>

music_app/app/views/bands/show.html.erb
<h1><%= @band.name %>'s Albums!</h1>
<br/>
<a href="<%= new_album_url %>" >Add an album!</a>
<br/>
<% @band.albums.each do |album| %>
<h3><a href="<%= band_album_url(@band.id, album.id) %>"><%= album.title %></a></h3>
<br/>
<% end %>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<style>
  html {
    background: url(/assets/<%= rand(12)+1 %>.jpeg) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    font: 1em Verdana,Arial,sans-serif;
  }
</style>
  <header>
      <section id="logo">
        <a href="/bands">MyMusic</a>
      </section>
      <section id="nav">
          <a href="<%= bands_url %>">See All Bands</a>
          <% if logged_in? %>
          <a href="<%= new_band_url %>" >Add a band!</a>
          <strong><a href="<%= user_url(current_user) %>"><%= current_user.email %></strong></a>
          <% else %>
            <a href="<%= new_user_url %>">Sign up!</a>
            <a href="<%= new_session_url %>">Sign In!</a>
          <% end %>
        </section>
  </header>


  <body>
        <br/>
        <br/>
    <%= yield %>
  </body>
</html>

music_app/app/views/shared/_errors.html.erb
<div id="errors">
        <% if flash[:errors] %>
            <br/>
            <% flash[:errors].each do |error| %>
            <%= error %>
            <% end %>
            <br/>
        <% end %>
</div>

music_app/app/views/shared/_form.html.erb
<% if form == 'login' %>
    <% action = session_url %>
    <% button_text = "Sign In!" %>
<% else %> 
    <% action = users_url %>
    <% button_text = "Sign Up!" %>
<% end %>

    <form id="login" action="<%= action %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= session[:authenticity_token] %>">
        <label for="email">
            Email 
            <br/>
            <input type="text" name="user[email]"> 
        </label>
        <br/>
        <br/>
        <label for="password">
            Password
            <br/>
            <input type="password" name="user[password]">
        </label>
        <br/>
        <br/>
        <input type="Submit" value="<%= button_text %>">    
        <%= render 'shared/errors', user: @user %>
    </form>

music_app/app/views/tracks/new.html.erb
<form id="login" action="<%= tracks_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= session[:authenticity_token] %>">
        <label for="album_id">
                Made By: 
                <select name="track[album_id]">
                        <option disabled selected> Choose an album </option>
                    <% Album.all.each do |album| %>
                        <option name="track[album_id]" value="<%= album.id %>"><%= album.title %></option>
                    <% end %>
                </select>
            </label>
            <br/>
        <label for="title">
            Track Name: 
            <input type="text" name="track[title]"> 
        </label>
        <br/>
        <label for="ord">
            Track Order: 
            <input type="text" name="track[ord]"> 
        </label>
        <br/>
        <label for="regular_bonus">
            Recorded: 
            <input type="radio" name="track[regular]" value="true">Regular</input>
            <input type="radio" name="track[regular]" value="false"> Bonus</input>
        </label>
        <br/>
        <br/>
        <input type="Submit" value="Add track">    
</form>

music_app/app/views/tracks/show.html.erb
<h1><%= @track.title %></h1>
<br/>
<div id="login">
Band: <%= Band.find_by(id: params[:band_id]).name %>
<br/>
Title: <%= @track.title %>
<br/>
Year Recorded: <%= @track.year %>
<br/>
track Type: <%= @track.studio ? "Studio" : "Live" %>
<br/>
</div>
<br/>

<form action="<%= track_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= session[:authenticity_token] %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Delete This track">
</form>

music_app/app/views/users/new.html.erb
<h1>Sign Up Now!</h1>
<br/>
<%= render 'shared/form', user: @user, form: 'signup' %>

music_app/app/views/users/show.html.erb
<div id="login">

<p>Nothing to display!</p>

<form action="<%= session_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= session[:authenticity_token] %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Sign Out">
</form>

</div>